/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.parser;

import jaca.lexer.*;
import jaca.node.*;
import jaca.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PDefClasse node1 = (PDefClasse) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AAclassedefclasse1DefClasse */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAclassedefclasse2DefClasse */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list, false);
            }
            break;
            case 2: /* reduce AAclassedefclasse3DefClasse */
            {
                ArrayList<Object> list = new2();
                push(goTo(0), list, false);
            }
            break;
            case 3: /* reduce AAclassedefclasse4DefClasse */
            {
                ArrayList<Object> list = new3();
                push(goTo(0), list, false);
            }
            break;
            case 4: /* reduce AIdClasseSeguinteIdClasseSeguinte */
            {
                ArrayList<Object> list = new4();
                push(goTo(1), list, false);
            }
            break;
            case 5: /* reduce ARelacaoInicialRelacaoInicial */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce ARelacoesSeguintesRelacoesSeguintes */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, false);
            }
            break;
            case 7: /* reduce AFamiliaFamilia */
            {
                ArrayList<Object> list = new7();
                push(goTo(4), list, false);
            }
            break;
            case 8: /* reduce AFamiliasFamilia */
            {
                ArrayList<Object> list = new8();
                push(goTo(4), list, false);
            }
            break;
            case 9: /* reduce ADecObjAtributos */
            {
                ArrayList<Object> list = new9();
                push(goTo(5), list, false);
            }
            break;
            case 10: /* reduce ADecVarAtributos */
            {
                ArrayList<Object> list = new10();
                push(goTo(5), list, false);
            }
            break;
            case 11: /* reduce ADecConsAtributos */
            {
                ArrayList<Object> list = new11();
                push(goTo(5), list, false);
            }
            break;
            case 12: /* reduce ADecObjSegAtributosSeguintes */
            {
                ArrayList<Object> list = new12();
                push(goTo(6), list, false);
            }
            break;
            case 13: /* reduce ADecVarSegAtributosSeguintes */
            {
                ArrayList<Object> list = new13();
                push(goTo(6), list, false);
            }
            break;
            case 14: /* reduce ADecConsSegAtributosSeguintes */
            {
                ArrayList<Object> list = new14();
                push(goTo(6), list, false);
            }
            break;
            case 15: /* reduce ADecProcedimentoMetodos */
            {
                ArrayList<Object> list = new15();
                push(goTo(7), list, false);
            }
            break;
            case 16: /* reduce ADecFuncaoMetodos */
            {
                ArrayList<Object> list = new16();
                push(goTo(7), list, false);
            }
            break;
            case 17: /* reduce ADecObjDecObj */
            {
                ArrayList<Object> list = new17();
                push(goTo(8), list, false);
            }
            break;
            case 18: /* reduce ADecVarRealDecVar */
            {
                ArrayList<Object> list = new18();
                push(goTo(9), list, false);
            }
            break;
            case 19: /* reduce ADecVarBoolDecVar */
            {
                ArrayList<Object> list = new19();
                push(goTo(9), list, false);
            }
            break;
            case 20: /* reduce ADecConstanteRealDecCons */
            {
                ArrayList<Object> list = new20();
                push(goTo(10), list, false);
            }
            break;
            case 21: /* reduce ADecConstanteBoolDecCons */
            {
                ArrayList<Object> list = new21();
                push(goTo(10), list, false);
            }
            break;
            case 22: /* reduce ADecFuncaoRealDecFuncao */
            {
                ArrayList<Object> list = new22();
                push(goTo(11), list, false);
            }
            break;
            case 23: /* reduce ADecFuncaoBooleanaDecFuncao */
            {
                ArrayList<Object> list = new23();
                push(goTo(11), list, false);
            }
            break;
            case 24: /* reduce ADecFuncaoRealExpDecFuncao */
            {
                ArrayList<Object> list = new24();
                push(goTo(11), list, false);
            }
            break;
            case 25: /* reduce ADecFuncaoBooleanaExpDecFuncao */
            {
                ArrayList<Object> list = new25();
                push(goTo(11), list, false);
            }
            break;
            case 26: /* reduce AParametroNuloParametros */
            {
                ArrayList<Object> list = new26();
                push(goTo(12), list, false);
            }
            break;
            case 27: /* reduce AParametroParametros */
            {
                ArrayList<Object> list = new27();
                push(goTo(12), list, false);
            }
            break;
            case 28: /* reduce AConjParametrosParametros */
            {
                ArrayList<Object> list = new28();
                push(goTo(12), list, false);
            }
            break;
            case 29: /* reduce AValorRealExp */
            {
                ArrayList<Object> list = new29();
                push(goTo(13), list, false);
            }
            break;
            case 30: /* reduce ABoolVerdadeExp */
            {
                ArrayList<Object> list = new30();
                push(goTo(13), list, false);
            }
            break;
            case 31: /* reduce ABoolFalsoExp */
            {
                ArrayList<Object> list = new31();
                push(goTo(13), list, false);
            }
            break;
            case 32: /* reduce AParametroBoolParametro */
            {
                ArrayList<Object> list = new32();
                push(goTo(14), list, false);
            }
            break;
            case 33: /* reduce AParametroRealParametro */
            {
                ArrayList<Object> list = new33();
                push(goTo(14), list, false);
            }
            break;
            case 34: /* reduce AParametroBoolParametroSeguinte */
            {
                ArrayList<Object> list = new34();
                push(goTo(15), list, false);
            }
            break;
            case 35: /* reduce AParametroRealParametroSeguinte */
            {
                ArrayList<Object> list = new35();
                push(goTo(15), list, false);
            }
            break;
            case 36: /* reduce AInicializarInicializar */
            {
                ArrayList<Object> list = new36();
                push(goTo(16), list, false);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AAclassedefclasse1DefClasse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDefClasse pdefclasseNode1;
        {
            // Block
        TClasse tclasseNode2;
        TIdClasse tidclasseNode3;
        TInicio tinicioNode4;
        @SuppressWarnings("unused") Object nullNode5 = null;
        @SuppressWarnings("unused") Object nullNode6 = null;
        TFim tfimNode7;
        tclasseNode2 = (TClasse)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tinicioNode4 = (TInicio)nodeArrayList3.get(0);
        tfimNode7 = (TFim)nodeArrayList4.get(0);

        pdefclasseNode1 = new AClasseDefClasse(tclasseNode2, tidclasseNode3, tinicioNode4, null, null, tfimNode7);
        }
	nodeList.add(pdefclasseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAclassedefclasse2DefClasse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDefClasse pdefclasseNode1;
        {
            // Block
        TClasse tclasseNode2;
        TIdClasse tidclasseNode3;
        TInicio tinicioNode4;
        PAtributos patributosNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        TFim tfimNode7;
        tclasseNode2 = (TClasse)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tinicioNode4 = (TInicio)nodeArrayList3.get(0);
        patributosNode5 = (PAtributos)nodeArrayList4.get(0);
        tfimNode7 = (TFim)nodeArrayList5.get(0);

        pdefclasseNode1 = new AClasseDefClasse(tclasseNode2, tidclasseNode3, tinicioNode4, patributosNode5, null, tfimNode7);
        }
	nodeList.add(pdefclasseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAclassedefclasse3DefClasse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDefClasse pdefclasseNode1;
        {
            // Block
        TClasse tclasseNode2;
        TIdClasse tidclasseNode3;
        TInicio tinicioNode4;
        @SuppressWarnings("unused") Object nullNode5 = null;
        PMetodos pmetodosNode6;
        TFim tfimNode7;
        tclasseNode2 = (TClasse)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tinicioNode4 = (TInicio)nodeArrayList3.get(0);
        pmetodosNode6 = (PMetodos)nodeArrayList4.get(0);
        tfimNode7 = (TFim)nodeArrayList5.get(0);

        pdefclasseNode1 = new AClasseDefClasse(tclasseNode2, tidclasseNode3, tinicioNode4, null, pmetodosNode6, tfimNode7);
        }
	nodeList.add(pdefclasseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAclassedefclasse4DefClasse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDefClasse pdefclasseNode1;
        {
            // Block
        TClasse tclasseNode2;
        TIdClasse tidclasseNode3;
        TInicio tinicioNode4;
        PAtributos patributosNode5;
        PMetodos pmetodosNode6;
        TFim tfimNode7;
        tclasseNode2 = (TClasse)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tinicioNode4 = (TInicio)nodeArrayList3.get(0);
        patributosNode5 = (PAtributos)nodeArrayList4.get(0);
        pmetodosNode6 = (PMetodos)nodeArrayList5.get(0);
        tfimNode7 = (TFim)nodeArrayList6.get(0);

        pdefclasseNode1 = new AClasseDefClasse(tclasseNode2, tidclasseNode3, tinicioNode4, patributosNode5, pmetodosNode6, tfimNode7);
        }
	nodeList.add(pdefclasseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AIdClasseSeguinteIdClasseSeguinte */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIdClasseSeguinte pidclasseseguinteNode1;
        {
            // Block
        TIdClasse tidclasseNode2;
        tidclasseNode2 = (TIdClasse)nodeArrayList1.get(0);

        pidclasseseguinteNode1 = new AIdClasseSeguinteIdClasseSeguinte(tidclasseNode2);
        }
	nodeList.add(pidclasseseguinteNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ARelacaoInicialRelacaoInicial */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelacaoInicial prelacaoinicialNode1;
        {
            // Block
        TClasse tclasseNode2;
        TIdClasse tidclasseNode3;
        TFilha tfilhaNode4;
        PIdClasseSeguinte pidclasseseguinteNode5;
        tclasseNode2 = (TClasse)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tfilhaNode4 = (TFilha)nodeArrayList3.get(0);
        pidclasseseguinteNode5 = (PIdClasseSeguinte)nodeArrayList4.get(0);

        prelacaoinicialNode1 = new ARelacaoInicialRelacaoInicial(tclasseNode2, tidclasseNode3, tfilhaNode4, pidclasseseguinteNode5);
        }
	nodeList.add(prelacaoinicialNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ARelacoesSeguintesRelacoesSeguintes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelacoesSeguintes prelacoesseguintesNode1;
        {
            // Block
        TClasse tclasseNode2;
        TIdClasse tidclasseNode3;
        TFilha tfilhaNode4;
        PIdClasseSeguinte pidclasseseguinteNode5;
        tclasseNode2 = (TClasse)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tfilhaNode4 = (TFilha)nodeArrayList3.get(0);
        pidclasseseguinteNode5 = (PIdClasseSeguinte)nodeArrayList4.get(0);

        prelacoesseguintesNode1 = new ARelacoesSeguintesRelacoesSeguintes(tclasseNode2, tidclasseNode3, tfilhaNode4, pidclasseseguinteNode5);
        }
	nodeList.add(prelacoesseguintesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AFamiliaFamilia */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFamilia pfamiliaNode1;
        {
            // Block
        PRelacaoInicial prelacaoinicialNode2;
        TPontoevirgula tpontoevirgulaNode3;
        prelacaoinicialNode2 = (PRelacaoInicial)nodeArrayList1.get(0);
        tpontoevirgulaNode3 = (TPontoevirgula)nodeArrayList2.get(0);

        pfamiliaNode1 = new AFamiliaFamilia(prelacaoinicialNode2, tpontoevirgulaNode3);
        }
	nodeList.add(pfamiliaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AFamiliasFamilia */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFamilia pfamiliaNode1;
        {
            // Block
        PRelacaoInicial prelacaoinicialNode2;
        TAmpersand tampersandNode3;
        PRelacoesSeguintes prelacoesseguintesNode4;
        TPontoevirgula tpontoevirgulaNode5;
        prelacaoinicialNode2 = (PRelacaoInicial)nodeArrayList1.get(0);
        tampersandNode3 = (TAmpersand)nodeArrayList2.get(0);
        prelacoesseguintesNode4 = (PRelacoesSeguintes)nodeArrayList3.get(0);
        tpontoevirgulaNode5 = (TPontoevirgula)nodeArrayList4.get(0);

        pfamiliaNode1 = new AFamiliasFamilia(prelacaoinicialNode2, tampersandNode3, prelacoesseguintesNode4, tpontoevirgulaNode5);
        }
	nodeList.add(pfamiliaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce ADecObjAtributos */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAtributos patributosNode1;
        {
            // Block
        PDecObj pdecobjNode2;
        PAtributosSeguintes patributosseguintesNode3;
        pdecobjNode2 = (PDecObj)nodeArrayList1.get(0);
        patributosseguintesNode3 = (PAtributosSeguintes)nodeArrayList2.get(0);

        patributosNode1 = new ADecObjAtributos(pdecobjNode2, patributosseguintesNode3);
        }
	nodeList.add(patributosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ADecVarAtributos */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAtributos patributosNode1;
        {
            // Block
        PDecVar pdecvarNode2;
        PAtributosSeguintes patributosseguintesNode3;
        pdecvarNode2 = (PDecVar)nodeArrayList1.get(0);
        patributosseguintesNode3 = (PAtributosSeguintes)nodeArrayList2.get(0);

        patributosNode1 = new ADecVarAtributos(pdecvarNode2, patributosseguintesNode3);
        }
	nodeList.add(patributosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ADecConsAtributos */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAtributos patributosNode1;
        {
            // Block
        PDecCons pdecconsNode2;
        PAtributosSeguintes patributosseguintesNode3;
        pdecconsNode2 = (PDecCons)nodeArrayList1.get(0);
        patributosseguintesNode3 = (PAtributosSeguintes)nodeArrayList2.get(0);

        patributosNode1 = new ADecConsAtributos(pdecconsNode2, patributosseguintesNode3);
        }
	nodeList.add(patributosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce ADecObjSegAtributosSeguintes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAtributosSeguintes patributosseguintesNode1;
        {
            // Block
        PDecObj pdecobjNode2;
        PAtributos patributosNode3;
        pdecobjNode2 = (PDecObj)nodeArrayList1.get(0);
        patributosNode3 = (PAtributos)nodeArrayList2.get(0);

        patributosseguintesNode1 = new ADecObjSegAtributosSeguintes(pdecobjNode2, patributosNode3);
        }
	nodeList.add(patributosseguintesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ADecVarSegAtributosSeguintes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAtributosSeguintes patributosseguintesNode1;
        {
            // Block
        PDecVar pdecvarNode2;
        PAtributos patributosNode3;
        pdecvarNode2 = (PDecVar)nodeArrayList1.get(0);
        patributosNode3 = (PAtributos)nodeArrayList2.get(0);

        patributosseguintesNode1 = new ADecVarSegAtributosSeguintes(pdecvarNode2, patributosNode3);
        }
	nodeList.add(patributosseguintesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ADecConsSegAtributosSeguintes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAtributosSeguintes patributosseguintesNode1;
        {
            // Block
        PDecCons pdecconsNode2;
        PAtributos patributosNode3;
        pdecconsNode2 = (PDecCons)nodeArrayList1.get(0);
        patributosNode3 = (PAtributos)nodeArrayList2.get(0);

        patributosseguintesNode1 = new ADecConsSegAtributosSeguintes(pdecconsNode2, patributosNode3);
        }
	nodeList.add(patributosseguintesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ADecProcedimentoMetodos */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMetodos pmetodosNode1;
        {
            // Block
        TDecProcedimento tdecprocedimentoNode2;
        tdecprocedimentoNode2 = (TDecProcedimento)nodeArrayList1.get(0);

        pmetodosNode1 = new ADecProcedimentoMetodos(tdecprocedimentoNode2);
        }
	nodeList.add(pmetodosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce ADecFuncaoMetodos */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMetodos pmetodosNode1;
        {
            // Block
        PDecFuncao pdecfuncaoNode2;
        pdecfuncaoNode2 = (PDecFuncao)nodeArrayList1.get(0);

        pmetodosNode1 = new ADecFuncaoMetodos(pdecfuncaoNode2);
        }
	nodeList.add(pmetodosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce ADecObjDecObj */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecObj pdecobjNode1;
        {
            // Block
        TObj tobjNode2;
        TIdClasse tidclasseNode3;
        TId tidNode4;
        TPontoevirgula tpontoevirgulaNode5;
        tobjNode2 = (TObj)nodeArrayList1.get(0);
        tidclasseNode3 = (TIdClasse)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tpontoevirgulaNode5 = (TPontoevirgula)nodeArrayList4.get(0);

        pdecobjNode1 = new ADecObjDecObj(tobjNode2, tidclasseNode3, tidNode4, tpontoevirgulaNode5);
        }
	nodeList.add(pdecobjNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce ADecVarRealDecVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecVar pdecvarNode1;
        {
            // Block
        TVar tvarNode2;
        TReal trealNode3;
        TId tidNode4;
        TPontoevirgula tpontoevirgulaNode5;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        trealNode3 = (TReal)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tpontoevirgulaNode5 = (TPontoevirgula)nodeArrayList4.get(0);

        pdecvarNode1 = new ADecVarRealDecVar(tvarNode2, trealNode3, tidNode4, tpontoevirgulaNode5);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce ADecVarBoolDecVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecVar pdecvarNode1;
        {
            // Block
        TVar tvarNode2;
        TBooleano tbooleanoNode3;
        TId tidNode4;
        TPontoevirgula tpontoevirgulaNode5;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tbooleanoNode3 = (TBooleano)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tpontoevirgulaNode5 = (TPontoevirgula)nodeArrayList4.get(0);

        pdecvarNode1 = new ADecVarBoolDecVar(tvarNode2, tbooleanoNode3, tidNode4, tpontoevirgulaNode5);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce ADecConstanteRealDecCons */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecCons pdecconsNode1;
        {
            // Block
        TConstante tconstanteNode2;
        TReal trealNode3;
        PInicializar pinicializarNode4;
        TPontoevirgula tpontoevirgulaNode5;
        tconstanteNode2 = (TConstante)nodeArrayList1.get(0);
        trealNode3 = (TReal)nodeArrayList2.get(0);
        pinicializarNode4 = (PInicializar)nodeArrayList3.get(0);
        tpontoevirgulaNode5 = (TPontoevirgula)nodeArrayList4.get(0);

        pdecconsNode1 = new ADecConstanteRealDecCons(tconstanteNode2, trealNode3, pinicializarNode4, tpontoevirgulaNode5);
        }
	nodeList.add(pdecconsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce ADecConstanteBoolDecCons */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecCons pdecconsNode1;
        {
            // Block
        TConstante tconstanteNode2;
        TBooleano tbooleanoNode3;
        PInicializar pinicializarNode4;
        TPontoevirgula tpontoevirgulaNode5;
        tconstanteNode2 = (TConstante)nodeArrayList1.get(0);
        tbooleanoNode3 = (TBooleano)nodeArrayList2.get(0);
        pinicializarNode4 = (PInicializar)nodeArrayList3.get(0);
        tpontoevirgulaNode5 = (TPontoevirgula)nodeArrayList4.get(0);

        pdecconsNode1 = new ADecConstanteBoolDecCons(tconstanteNode2, tbooleanoNode3, pinicializarNode4, tpontoevirgulaNode5);
        }
	nodeList.add(pdecconsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce ADecFuncaoRealDecFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecFuncao pdecfuncaoNode1;
        {
            // Block
        TFuncao tfuncaoNode2;
        TReal trealNode3;
        TId tidNode4;
        TParEsq tparesqNode5;
        PParametros pparametrosNode6;
        TParDir tpardirNode7;
        TPontoevirgula tpontoevirgulaNode8;
        tfuncaoNode2 = (TFuncao)nodeArrayList1.get(0);
        trealNode3 = (TReal)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tparesqNode5 = (TParEsq)nodeArrayList4.get(0);
        pparametrosNode6 = (PParametros)nodeArrayList5.get(0);
        tpardirNode7 = (TParDir)nodeArrayList6.get(0);
        tpontoevirgulaNode8 = (TPontoevirgula)nodeArrayList7.get(0);

        pdecfuncaoNode1 = new ADecFuncaoRealDecFuncao(tfuncaoNode2, trealNode3, tidNode4, tparesqNode5, pparametrosNode6, tpardirNode7, tpontoevirgulaNode8);
        }
	nodeList.add(pdecfuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce ADecFuncaoBooleanaDecFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecFuncao pdecfuncaoNode1;
        {
            // Block
        TFuncao tfuncaoNode2;
        TBooleano tbooleanoNode3;
        TId tidNode4;
        TParEsq tparesqNode5;
        PParametros pparametrosNode6;
        TParDir tpardirNode7;
        TPontoevirgula tpontoevirgulaNode8;
        tfuncaoNode2 = (TFuncao)nodeArrayList1.get(0);
        tbooleanoNode3 = (TBooleano)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tparesqNode5 = (TParEsq)nodeArrayList4.get(0);
        pparametrosNode6 = (PParametros)nodeArrayList5.get(0);
        tpardirNode7 = (TParDir)nodeArrayList6.get(0);
        tpontoevirgulaNode8 = (TPontoevirgula)nodeArrayList7.get(0);

        pdecfuncaoNode1 = new ADecFuncaoBooleanaDecFuncao(tfuncaoNode2, tbooleanoNode3, tidNode4, tparesqNode5, pparametrosNode6, tpardirNode7, tpontoevirgulaNode8);
        }
	nodeList.add(pdecfuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce ADecFuncaoRealExpDecFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecFuncao pdecfuncaoNode1;
        {
            // Block
        TFuncao tfuncaoNode2;
        TReal trealNode3;
        TId tidNode4;
        TParEsq tparesqNode5;
        PParametros pparametrosNode6;
        TParDir tpardirNode7;
        PExp pexpNode8;
        tfuncaoNode2 = (TFuncao)nodeArrayList1.get(0);
        trealNode3 = (TReal)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tparesqNode5 = (TParEsq)nodeArrayList4.get(0);
        pparametrosNode6 = (PParametros)nodeArrayList5.get(0);
        tpardirNode7 = (TParDir)nodeArrayList6.get(0);
        pexpNode8 = (PExp)nodeArrayList7.get(0);

        pdecfuncaoNode1 = new ADecFuncaoRealExpDecFuncao(tfuncaoNode2, trealNode3, tidNode4, tparesqNode5, pparametrosNode6, tpardirNode7, pexpNode8);
        }
	nodeList.add(pdecfuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce ADecFuncaoBooleanaExpDecFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecFuncao pdecfuncaoNode1;
        {
            // Block
        TFuncao tfuncaoNode2;
        TBooleano tbooleanoNode3;
        TId tidNode4;
        TParEsq tparesqNode5;
        PParametros pparametrosNode6;
        TParDir tpardirNode7;
        PExp pexpNode8;
        tfuncaoNode2 = (TFuncao)nodeArrayList1.get(0);
        tbooleanoNode3 = (TBooleano)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tparesqNode5 = (TParEsq)nodeArrayList4.get(0);
        pparametrosNode6 = (PParametros)nodeArrayList5.get(0);
        tpardirNode7 = (TParDir)nodeArrayList6.get(0);
        pexpNode8 = (PExp)nodeArrayList7.get(0);

        pdecfuncaoNode1 = new ADecFuncaoBooleanaExpDecFuncao(tfuncaoNode2, tbooleanoNode3, tidNode4, tparesqNode5, pparametrosNode6, tpardirNode7, pexpNode8);
        }
	nodeList.add(pdecfuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce AParametroNuloParametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametros pparametrosNode1;
        {
            // Block
        TVazioNIgnorado tvazionignoradoNode2;
        tvazionignoradoNode2 = (TVazioNIgnorado)nodeArrayList1.get(0);

        pparametrosNode1 = new AParametroNuloParametros(tvazionignoradoNode2);
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AParametroParametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametros pparametrosNode1;
        {
            // Block
        PParametro pparametroNode2;
        pparametroNode2 = (PParametro)nodeArrayList1.get(0);

        pparametrosNode1 = new AParametroParametros(pparametroNode2);
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AConjParametrosParametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametros pparametrosNode1;
        {
            // Block
        PParametro pparametroNode2;
        TBarra tbarraNode3;
        PParametroSeguinte pparametroseguinteNode4;
        pparametroNode2 = (PParametro)nodeArrayList1.get(0);
        tbarraNode3 = (TBarra)nodeArrayList2.get(0);
        pparametroseguinteNode4 = (PParametroSeguinte)nodeArrayList3.get(0);

        pparametrosNode1 = new AConjParametrosParametros(pparametroNode2, tbarraNode3, pparametroseguinteNode4);
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AValorRealExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TReal trealNode2;
        trealNode2 = (TReal)nodeArrayList1.get(0);

        pexpNode1 = new AValorRealExp(trealNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce ABoolVerdadeExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TVerdade tverdadeNode2;
        tverdadeNode2 = (TVerdade)nodeArrayList1.get(0);

        pexpNode1 = new ABoolVerdadeExp(tverdadeNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce ABoolFalsoExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TFalso tfalsoNode2;
        tfalsoNode2 = (TFalso)nodeArrayList1.get(0);

        pexpNode1 = new ABoolFalsoExp(tfalsoNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AParametroBoolParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametro pparametroNode1;
        {
            // Block
        TBooleano tbooleanoNode2;
        TId tidNode3;
        tbooleanoNode2 = (TBooleano)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pparametroNode1 = new AParametroBoolParametro(tbooleanoNode2, tidNode3);
        }
	nodeList.add(pparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AParametroRealParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametro pparametroNode1;
        {
            // Block
        TReal trealNode2;
        TId tidNode3;
        trealNode2 = (TReal)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pparametroNode1 = new AParametroRealParametro(trealNode2, tidNode3);
        }
	nodeList.add(pparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AParametroBoolParametroSeguinte */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametroSeguinte pparametroseguinteNode1;
        {
            // Block
        TBooleano tbooleanoNode2;
        TId tidNode3;
        tbooleanoNode2 = (TBooleano)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pparametroseguinteNode1 = new AParametroBoolParametroSeguinte(tbooleanoNode2, tidNode3);
        }
	nodeList.add(pparametroseguinteNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AParametroRealParametroSeguinte */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametroSeguinte pparametroseguinteNode1;
        {
            // Block
        TReal trealNode2;
        TId tidNode3;
        trealNode2 = (TReal)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pparametroseguinteNode1 = new AParametroRealParametroSeguinte(trealNode2, tidNode3);
        }
	nodeList.add(pparametroseguinteNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AInicializarInicializar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInicializar pinicializarNode1;
        {
            // Block
        TId tidNode2;
        TInicializacao tinicializacaoNode3;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tinicializacaoNode3 = (TInicializacao)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pinicializarNode1 = new AInicializarInicializar(tidNode2, tinicializacaoNode3, pexpNode4);
        }
	nodeList.add(pinicializarNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {25, SHIFT, 3}, },
			{{-1, ERROR, 2}, {41, ACCEPT, -1}, },
			{{-1, ERROR, 3}, {6, SHIFT, 4}, },
			{{-1, ERROR, 4}, {5, SHIFT, 5}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, {13, SHIFT, 9}, {15, SHIFT, 10}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 6}, {25, SHIFT, 17}, },
			{{-1, ERROR, 7}, {11, SHIFT, 18}, {12, SHIFT, 19}, },
			{{-1, ERROR, 8}, {11, SHIFT, 20}, {12, SHIFT, 21}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 10}, {11, SHIFT, 22}, {12, SHIFT, 23}, },
			{{-1, ERROR, 11}, {5, SHIFT, 24}, {13, SHIFT, 9}, {15, SHIFT, 10}, },
			{{-1, ERROR, 12}, {5, SHIFT, 26}, },
			{{-1, ERROR, 13}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, },
			{{-1, ERROR, 14}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, },
			{{-1, ERROR, 15}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 17}, {24, SHIFT, 33}, },
			{{-1, ERROR, 18}, {24, SHIFT, 34}, },
			{{-1, ERROR, 19}, {24, SHIFT, 35}, },
			{{-1, ERROR, 20}, {24, SHIFT, 36}, },
			{{-1, ERROR, 21}, {24, SHIFT, 36}, },
			{{-1, ERROR, 22}, {24, SHIFT, 39}, },
			{{-1, ERROR, 23}, {24, SHIFT, 40}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 25}, {5, SHIFT, 41}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 28}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, },
			{{-1, ERROR, 29}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, },
			{{-1, ERROR, 30}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 33}, {4, SHIFT, 45}, },
			{{-1, ERROR, 34}, {4, SHIFT, 46}, },
			{{-1, ERROR, 35}, {4, SHIFT, 47}, },
			{{-1, ERROR, 36}, {10, SHIFT, 48}, },
			{{-1, ERROR, 37}, {4, SHIFT, 49}, },
			{{-1, ERROR, 38}, {4, SHIFT, 50}, },
			{{-1, ERROR, 39}, {37, SHIFT, 51}, },
			{{-1, ERROR, 40}, {37, SHIFT, 52}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 48}, {12, SHIFT, 53}, {21, SHIFT, 54}, {22, SHIFT, 55}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 51}, {11, SHIFT, 57}, {12, SHIFT, 58}, {40, SHIFT, 59}, },
			{{-1, ERROR, 52}, {11, SHIFT, 57}, {12, SHIFT, 58}, {40, SHIFT, 59}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 36}, },
			{{-1, ERROR, 57}, {24, SHIFT, 63}, },
			{{-1, ERROR, 58}, {24, SHIFT, 64}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 60}, {38, SHIFT, 65}, },
			{{-1, REDUCE, 27}, {39, SHIFT, 66}, },
			{{-1, ERROR, 62}, {38, SHIFT, 67}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 33}, },
			{{-1, ERROR, 65}, {4, SHIFT, 68}, {12, SHIFT, 53}, {21, SHIFT, 54}, {22, SHIFT, 55}, },
			{{-1, ERROR, 66}, {11, SHIFT, 70}, {12, SHIFT, 71}, },
			{{-1, ERROR, 67}, {4, SHIFT, 73}, {12, SHIFT, 53}, {21, SHIFT, 54}, {22, SHIFT, 55}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 70}, {24, SHIFT, 75}, },
			{{-1, ERROR, 71}, {24, SHIFT, 76}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 35}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, 11}, {28, 42}, {29, 43}, {30, 44}, },
			{{-1, 27}, {14, 31}, {15, 32}, },
			{{-1, 12}, {11, 25}, },
			{{-1, 13}, {13, 28}, {14, 28}, {15, 28}, },
			{{-1, 14}, {13, 29}, {14, 29}, {15, 29}, },
			{{-1, 15}, {13, 30}, {14, 30}, {15, 30}, },
			{{-1, 16}, },
			{{-1, 60}, {52, 62}, },
			{{-1, 56}, {65, 69}, {67, 74}, },
			{{-1, 61}, },
			{{-1, 72}, },
			{{-1, 37}, {21, 38}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'classe'",
			"expecting: id classe",
			"expecting: EOF",
			"expecting: 'início'",
			"expecting: 'fim', 'objeto', 'var', 'const', '>>>', 'função'",
			"expecting: 'bool', 'real'",
			"expecting: 'fim'",
			"expecting: 'fim', '>>>', 'função'",
			"expecting: 'objeto', 'var', 'const'",
			"expecting: id",
			"expecting: ';'",
			"expecting: ':='",
			"expecting: '('",
			"expecting: 'real', 'verdade', 'falso'",
			"expecting: 'bool', 'real', vazio n ignorado",
			"expecting: ';', 'fim'",
			"expecting: ')'",
			"expecting: ')', '|'",
			"expecting: ';', 'real', 'verdade', 'falso'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 2, 1, 5, 5, 6, 5, 7, 6, 8, 8, 8, 6, 9, 9, 9, 9, 9, 9, 9, 2, 6, 2, 7, 8, 8, 8, 7, 7, 10, 10, 10, 11, 10, 10, 12, 12, 2, 7, 7, 7, 8, 8, 8, 13, 8, 8, 14, 14, 15, 15, 15, 10, 9, 9, 16, 16, 17, 16, 17, 17, 18, 5, 18, 6, 6, 9, 9, 16, 6, 6, 16, 16, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
