/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AAtributoIdExp extends PExp
{
    private PChamadaOpcional _chamadaOpcional_;
    private PAtributo _atributo_;
    private TPontoevirgula _pontoevirgula_;

    public AAtributoIdExp()
    {
        // Constructor
    }

    public AAtributoIdExp(
        @SuppressWarnings("hiding") PChamadaOpcional _chamadaOpcional_,
        @SuppressWarnings("hiding") PAtributo _atributo_,
        @SuppressWarnings("hiding") TPontoevirgula _pontoevirgula_)
    {
        // Constructor
        setChamadaOpcional(_chamadaOpcional_);

        setAtributo(_atributo_);

        setPontoevirgula(_pontoevirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAtributoIdExp(
            cloneNode(this._chamadaOpcional_),
            cloneNode(this._atributo_),
            cloneNode(this._pontoevirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributoIdExp(this);
    }

    public PChamadaOpcional getChamadaOpcional()
    {
        return this._chamadaOpcional_;
    }

    public void setChamadaOpcional(PChamadaOpcional node)
    {
        if(this._chamadaOpcional_ != null)
        {
            this._chamadaOpcional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamadaOpcional_ = node;
    }

    public PAtributo getAtributo()
    {
        return this._atributo_;
    }

    public void setAtributo(PAtributo node)
    {
        if(this._atributo_ != null)
        {
            this._atributo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributo_ = node;
    }

    public TPontoevirgula getPontoevirgula()
    {
        return this._pontoevirgula_;
    }

    public void setPontoevirgula(TPontoevirgula node)
    {
        if(this._pontoevirgula_ != null)
        {
            this._pontoevirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoevirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamadaOpcional_)
            + toString(this._atributo_)
            + toString(this._pontoevirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamadaOpcional_ == child)
        {
            this._chamadaOpcional_ = null;
            return;
        }

        if(this._atributo_ == child)
        {
            this._atributo_ = null;
            return;
        }

        if(this._pontoevirgula_ == child)
        {
            this._pontoevirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamadaOpcional_ == oldChild)
        {
            setChamadaOpcional((PChamadaOpcional) newChild);
            return;
        }

        if(this._atributo_ == oldChild)
        {
            setAtributo((PAtributo) newChild);
            return;
        }

        if(this._pontoevirgula_ == oldChild)
        {
            setPontoevirgula((TPontoevirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
