/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import java.util.*;
import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AAtributosEstruturaBloco extends PEstruturaBloco
{
    private final LinkedList<PAtributos> _atributos_ = new LinkedList<PAtributos>();

    public AAtributosEstruturaBloco()
    {
        // Constructor
    }

    public AAtributosEstruturaBloco(
        @SuppressWarnings("hiding") List<?> _atributos_)
    {
        // Constructor
        setAtributos(_atributos_);

    }

    @Override
    public Object clone()
    {
        return new AAtributosEstruturaBloco(
            cloneList(this._atributos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributosEstruturaBloco(this);
    }

    public LinkedList<PAtributos> getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(List<?> list)
    {
        for(PAtributos e : this._atributos_)
        {
            e.parent(null);
        }
        this._atributos_.clear();

        for(Object obj_e : list)
        {
            PAtributos e = (PAtributos) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._atributos_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atributos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atributos_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAtributos> i = this._atributos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAtributos) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
