/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AComandoBlocoAux extends PBlocoAux
{
    private PComandoAux _comandoAux_;

    public AComandoBlocoAux()
    {
        // Constructor
    }

    public AComandoBlocoAux(
        @SuppressWarnings("hiding") PComandoAux _comandoAux_)
    {
        // Constructor
        setComandoAux(_comandoAux_);

    }

    @Override
    public Object clone()
    {
        return new AComandoBlocoAux(
            cloneNode(this._comandoAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoBlocoAux(this);
    }

    public PComandoAux getComandoAux()
    {
        return this._comandoAux_;
    }

    public void setComandoAux(PComandoAux node)
    {
        if(this._comandoAux_ != null)
        {
            this._comandoAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAux_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoAux_ == child)
        {
            this._comandoAux_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoAux_ == oldChild)
        {
            setComandoAux((PComandoAux) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
