/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AConjParametrosParametros extends PParametros
{
    private PParametro _esq_;
    private TBarra _barra_;
    private PParametro _dir_;

    public AConjParametrosParametros()
    {
        // Constructor
    }

    public AConjParametrosParametros(
        @SuppressWarnings("hiding") PParametro _esq_,
        @SuppressWarnings("hiding") TBarra _barra_,
        @SuppressWarnings("hiding") PParametro _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setBarra(_barra_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AConjParametrosParametros(
            cloneNode(this._esq_),
            cloneNode(this._barra_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConjParametrosParametros(this);
    }

    public PParametro getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PParametro node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public TBarra getBarra()
    {
        return this._barra_;
    }

    public void setBarra(TBarra node)
    {
        if(this._barra_ != null)
        {
            this._barra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barra_ = node;
    }

    public PParametro getDir()
    {
        return this._dir_;
    }

    public void setDir(PParametro node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._barra_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._barra_ == child)
        {
            this._barra_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PParametro) newChild);
            return;
        }

        if(this._barra_ == oldChild)
        {
            setBarra((TBarra) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
