/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ADecConstanteRealDecCons extends PDecCons
{
    private TConstante _constante_;
    private PTipoPrimitivo _tipoPrimitivo_;
    private PInicializar _inicializar_;
    private TPontoevirgula _pontoevirgula_;

    public ADecConstanteRealDecCons()
    {
        // Constructor
    }

    public ADecConstanteRealDecCons(
        @SuppressWarnings("hiding") TConstante _constante_,
        @SuppressWarnings("hiding") PTipoPrimitivo _tipoPrimitivo_,
        @SuppressWarnings("hiding") PInicializar _inicializar_,
        @SuppressWarnings("hiding") TPontoevirgula _pontoevirgula_)
    {
        // Constructor
        setConstante(_constante_);

        setTipoPrimitivo(_tipoPrimitivo_);

        setInicializar(_inicializar_);

        setPontoevirgula(_pontoevirgula_);

    }

    @Override
    public Object clone()
    {
        return new ADecConstanteRealDecCons(
            cloneNode(this._constante_),
            cloneNode(this._tipoPrimitivo_),
            cloneNode(this._inicializar_),
            cloneNode(this._pontoevirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecConstanteRealDecCons(this);
    }

    public TConstante getConstante()
    {
        return this._constante_;
    }

    public void setConstante(TConstante node)
    {
        if(this._constante_ != null)
        {
            this._constante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constante_ = node;
    }

    public PTipoPrimitivo getTipoPrimitivo()
    {
        return this._tipoPrimitivo_;
    }

    public void setTipoPrimitivo(PTipoPrimitivo node)
    {
        if(this._tipoPrimitivo_ != null)
        {
            this._tipoPrimitivo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoPrimitivo_ = node;
    }

    public PInicializar getInicializar()
    {
        return this._inicializar_;
    }

    public void setInicializar(PInicializar node)
    {
        if(this._inicializar_ != null)
        {
            this._inicializar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicializar_ = node;
    }

    public TPontoevirgula getPontoevirgula()
    {
        return this._pontoevirgula_;
    }

    public void setPontoevirgula(TPontoevirgula node)
    {
        if(this._pontoevirgula_ != null)
        {
            this._pontoevirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoevirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constante_)
            + toString(this._tipoPrimitivo_)
            + toString(this._inicializar_)
            + toString(this._pontoevirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constante_ == child)
        {
            this._constante_ = null;
            return;
        }

        if(this._tipoPrimitivo_ == child)
        {
            this._tipoPrimitivo_ = null;
            return;
        }

        if(this._inicializar_ == child)
        {
            this._inicializar_ = null;
            return;
        }

        if(this._pontoevirgula_ == child)
        {
            this._pontoevirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constante_ == oldChild)
        {
            setConstante((TConstante) newChild);
            return;
        }

        if(this._tipoPrimitivo_ == oldChild)
        {
            setTipoPrimitivo((PTipoPrimitivo) newChild);
            return;
        }

        if(this._inicializar_ == oldChild)
        {
            setInicializar((PInicializar) newChild);
            return;
        }

        if(this._pontoevirgula_ == oldChild)
        {
            setPontoevirgula((TPontoevirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
