/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ADecConsAtributos extends PAtributos
{
    private PDecCons _decCons_;
    private PAtributos _atributos_;

    public ADecConsAtributos()
    {
        // Constructor
    }

    public ADecConsAtributos(
        @SuppressWarnings("hiding") PDecCons _decCons_,
        @SuppressWarnings("hiding") PAtributos _atributos_)
    {
        // Constructor
        setDecCons(_decCons_);

        setAtributos(_atributos_);

    }

    @Override
    public Object clone()
    {
        return new ADecConsAtributos(
            cloneNode(this._decCons_),
            cloneNode(this._atributos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecConsAtributos(this);
    }

    public PDecCons getDecCons()
    {
        return this._decCons_;
    }

    public void setDecCons(PDecCons node)
    {
        if(this._decCons_ != null)
        {
            this._decCons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decCons_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decCons_)
            + toString(this._atributos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decCons_ == child)
        {
            this._decCons_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decCons_ == oldChild)
        {
            setDecCons((PDecCons) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
