/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ADecVarAtributos extends PAtributos
{
    private PDecVar _decVar_;
    private PAtributos _atributos_;

    public ADecVarAtributos()
    {
        // Constructor
    }

    public ADecVarAtributos(
        @SuppressWarnings("hiding") PDecVar _decVar_,
        @SuppressWarnings("hiding") PAtributos _atributos_)
    {
        // Constructor
        setDecVar(_decVar_);

        setAtributos(_atributos_);

    }

    @Override
    public Object clone()
    {
        return new ADecVarAtributos(
            cloneNode(this._decVar_),
            cloneNode(this._atributos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecVarAtributos(this);
    }

    public PDecVar getDecVar()
    {
        return this._decVar_;
    }

    public void setDecVar(PDecVar node)
    {
        if(this._decVar_ != null)
        {
            this._decVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVar_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVar_)
            + toString(this._atributos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVar_ == child)
        {
            this._decVar_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decVar_ == oldChild)
        {
            setDecVar((PDecVar) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
