/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AFamiliasFamilia extends PFamilia
{
    private PRelacao _ini_;
    private TAmpersand _ampersand_;
    private PRelacao _fim_;
    private TPontoevirgula _pontoevirgula_;

    public AFamiliasFamilia()
    {
        // Constructor
    }

    public AFamiliasFamilia(
        @SuppressWarnings("hiding") PRelacao _ini_,
        @SuppressWarnings("hiding") TAmpersand _ampersand_,
        @SuppressWarnings("hiding") PRelacao _fim_,
        @SuppressWarnings("hiding") TPontoevirgula _pontoevirgula_)
    {
        // Constructor
        setIni(_ini_);

        setAmpersand(_ampersand_);

        setFim(_fim_);

        setPontoevirgula(_pontoevirgula_);

    }

    @Override
    public Object clone()
    {
        return new AFamiliasFamilia(
            cloneNode(this._ini_),
            cloneNode(this._ampersand_),
            cloneNode(this._fim_),
            cloneNode(this._pontoevirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFamiliasFamilia(this);
    }

    public PRelacao getIni()
    {
        return this._ini_;
    }

    public void setIni(PRelacao node)
    {
        if(this._ini_ != null)
        {
            this._ini_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ini_ = node;
    }

    public TAmpersand getAmpersand()
    {
        return this._ampersand_;
    }

    public void setAmpersand(TAmpersand node)
    {
        if(this._ampersand_ != null)
        {
            this._ampersand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ampersand_ = node;
    }

    public PRelacao getFim()
    {
        return this._fim_;
    }

    public void setFim(PRelacao node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    public TPontoevirgula getPontoevirgula()
    {
        return this._pontoevirgula_;
    }

    public void setPontoevirgula(TPontoevirgula node)
    {
        if(this._pontoevirgula_ != null)
        {
            this._pontoevirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoevirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ini_)
            + toString(this._ampersand_)
            + toString(this._fim_)
            + toString(this._pontoevirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ini_ == child)
        {
            this._ini_ = null;
            return;
        }

        if(this._ampersand_ == child)
        {
            this._ampersand_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        if(this._pontoevirgula_ == child)
        {
            this._pontoevirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ini_ == oldChild)
        {
            setIni((PRelacao) newChild);
            return;
        }

        if(this._ampersand_ == oldChild)
        {
            setAmpersand((TAmpersand) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((PRelacao) newChild);
            return;
        }

        if(this._pontoevirgula_ == oldChild)
        {
            setPontoevirgula((TPontoevirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
