/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AInicioBlocoAux extends PBlocoAux
{
    private TInicio _inicio_;

    public AInicioBlocoAux()
    {
        // Constructor
    }

    public AInicioBlocoAux(
        @SuppressWarnings("hiding") TInicio _inicio_)
    {
        // Constructor
        setInicio(_inicio_);

    }

    @Override
    public Object clone()
    {
        return new AInicioBlocoAux(
            cloneNode(this._inicio_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInicioBlocoAux(this);
    }

    public TInicio getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(TInicio node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inicio_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inicio_ == oldChild)
        {
            setInicio((TInicio) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
