/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AListasExpListasExp extends PListasExp
{
    private TBarra _barra_;
    private PListaExp _listaExp_;

    public AListasExpListasExp()
    {
        // Constructor
    }

    public AListasExpListasExp(
        @SuppressWarnings("hiding") TBarra _barra_,
        @SuppressWarnings("hiding") PListaExp _listaExp_)
    {
        // Constructor
        setBarra(_barra_);

        setListaExp(_listaExp_);

    }

    @Override
    public Object clone()
    {
        return new AListasExpListasExp(
            cloneNode(this._barra_),
            cloneNode(this._listaExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListasExpListasExp(this);
    }

    public TBarra getBarra()
    {
        return this._barra_;
    }

    public void setBarra(TBarra node)
    {
        if(this._barra_ != null)
        {
            this._barra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barra_ = node;
    }

    public PListaExp getListaExp()
    {
        return this._listaExp_;
    }

    public void setListaExp(PListaExp node)
    {
        if(this._listaExp_ != null)
        {
            this._listaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barra_)
            + toString(this._listaExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barra_ == child)
        {
            this._barra_ = null;
            return;
        }

        if(this._listaExp_ == child)
        {
            this._listaExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barra_ == oldChild)
        {
            setBarra((TBarra) newChild);
            return;
        }

        if(this._listaExp_ == oldChild)
        {
            setListaExp((PListaExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
