/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import java.util.*;
import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AProgramaPrograma extends PPrograma
{
    private PFamilia _familia_;
    private PDefClasse _ini_;
    private final LinkedList<PDefClasse> _fim_ = new LinkedList<PDefClasse>();

    public AProgramaPrograma()
    {
        // Constructor
    }

    public AProgramaPrograma(
        @SuppressWarnings("hiding") PFamilia _familia_,
        @SuppressWarnings("hiding") PDefClasse _ini_,
        @SuppressWarnings("hiding") List<?> _fim_)
    {
        // Constructor
        setFamilia(_familia_);

        setIni(_ini_);

        setFim(_fim_);

    }

    @Override
    public Object clone()
    {
        return new AProgramaPrograma(
            cloneNode(this._familia_),
            cloneNode(this._ini_),
            cloneList(this._fim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramaPrograma(this);
    }

    public PFamilia getFamilia()
    {
        return this._familia_;
    }

    public void setFamilia(PFamilia node)
    {
        if(this._familia_ != null)
        {
            this._familia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._familia_ = node;
    }

    public PDefClasse getIni()
    {
        return this._ini_;
    }

    public void setIni(PDefClasse node)
    {
        if(this._ini_ != null)
        {
            this._ini_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ini_ = node;
    }

    public LinkedList<PDefClasse> getFim()
    {
        return this._fim_;
    }

    public void setFim(List<?> list)
    {
        for(PDefClasse e : this._fim_)
        {
            e.parent(null);
        }
        this._fim_.clear();

        for(Object obj_e : list)
        {
            PDefClasse e = (PDefClasse) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._fim_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._familia_)
            + toString(this._ini_)
            + toString(this._fim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._familia_ == child)
        {
            this._familia_ = null;
            return;
        }

        if(this._ini_ == child)
        {
            this._ini_ = null;
            return;
        }

        if(this._fim_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._familia_ == oldChild)
        {
            setFamilia((PFamilia) newChild);
            return;
        }

        if(this._ini_ == oldChild)
        {
            setIni((PDefClasse) newChild);
            return;
        }

        for(ListIterator<PDefClasse> i = this._fim_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDefClasse) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
