/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ARelacoesRelacoes extends PRelacoes
{
    private TAmpersand _ampersand_;
    private PRelacao _relacao_;

    public ARelacoesRelacoes()
    {
        // Constructor
    }

    public ARelacoesRelacoes(
        @SuppressWarnings("hiding") TAmpersand _ampersand_,
        @SuppressWarnings("hiding") PRelacao _relacao_)
    {
        // Constructor
        setAmpersand(_ampersand_);

        setRelacao(_relacao_);

    }

    @Override
    public Object clone()
    {
        return new ARelacoesRelacoes(
            cloneNode(this._ampersand_),
            cloneNode(this._relacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacoesRelacoes(this);
    }

    public TAmpersand getAmpersand()
    {
        return this._ampersand_;
    }

    public void setAmpersand(TAmpersand node)
    {
        if(this._ampersand_ != null)
        {
            this._ampersand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ampersand_ = node;
    }

    public PRelacao getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(PRelacao node)
    {
        if(this._relacao_ != null)
        {
            this._relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ampersand_)
            + toString(this._relacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ampersand_ == child)
        {
            this._ampersand_ = null;
            return;
        }

        if(this._relacao_ == child)
        {
            this._relacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ampersand_ == oldChild)
        {
            setAmpersand((TAmpersand) newChild);
            return;
        }

        if(this._relacao_ == oldChild)
        {
            setRelacao((PRelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
