/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ARelacaoRelacao extends PRelacao
{
    private TClasse _classe_;
    private TIdClasse _ini_;
    private TFilha _filha_;
    private TIdClasse _fim_;

    public ARelacaoRelacao()
    {
        // Constructor
    }

    public ARelacaoRelacao(
        @SuppressWarnings("hiding") TClasse _classe_,
        @SuppressWarnings("hiding") TIdClasse _ini_,
        @SuppressWarnings("hiding") TFilha _filha_,
        @SuppressWarnings("hiding") TIdClasse _fim_)
    {
        // Constructor
        setClasse(_classe_);

        setIni(_ini_);

        setFilha(_filha_);

        setFim(_fim_);

    }

    @Override
    public Object clone()
    {
        return new ARelacaoRelacao(
            cloneNode(this._classe_),
            cloneNode(this._ini_),
            cloneNode(this._filha_),
            cloneNode(this._fim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacaoRelacao(this);
    }

    public TClasse getClasse()
    {
        return this._classe_;
    }

    public void setClasse(TClasse node)
    {
        if(this._classe_ != null)
        {
            this._classe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classe_ = node;
    }

    public TIdClasse getIni()
    {
        return this._ini_;
    }

    public void setIni(TIdClasse node)
    {
        if(this._ini_ != null)
        {
            this._ini_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ini_ = node;
    }

    public TFilha getFilha()
    {
        return this._filha_;
    }

    public void setFilha(TFilha node)
    {
        if(this._filha_ != null)
        {
            this._filha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filha_ = node;
    }

    public TIdClasse getFim()
    {
        return this._fim_;
    }

    public void setFim(TIdClasse node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classe_)
            + toString(this._ini_)
            + toString(this._filha_)
            + toString(this._fim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classe_ == child)
        {
            this._classe_ = null;
            return;
        }

        if(this._ini_ == child)
        {
            this._ini_ = null;
            return;
        }

        if(this._filha_ == child)
        {
            this._filha_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classe_ == oldChild)
        {
            setClasse((TClasse) newChild);
            return;
        }

        if(this._ini_ == oldChild)
        {
            setIni((TIdClasse) newChild);
            return;
        }

        if(this._filha_ == oldChild)
        {
            setFilha((TFilha) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((TIdClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
