/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ASenaoComando extends PComando
{
    private PEstruturaSenao _estruturaSenao_;
    private PComando _comando_;

    public ASenaoComando()
    {
        // Constructor
    }

    public ASenaoComando(
        @SuppressWarnings("hiding") PEstruturaSenao _estruturaSenao_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setEstruturaSenao(_estruturaSenao_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoComando(
            cloneNode(this._estruturaSenao_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoComando(this);
    }

    public PEstruturaSenao getEstruturaSenao()
    {
        return this._estruturaSenao_;
    }

    public void setEstruturaSenao(PEstruturaSenao node)
    {
        if(this._estruturaSenao_ != null)
        {
            this._estruturaSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._estruturaSenao_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._estruturaSenao_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._estruturaSenao_ == child)
        {
            this._estruturaSenao_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._estruturaSenao_ == oldChild)
        {
            setEstruturaSenao((PEstruturaSenao) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
