/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ASenaoAuxSenaoComandoAux extends PSenaoComandoAux
{
    private TSenao _senao_;
    private PComandoAux _comandoAux_;

    public ASenaoAuxSenaoComandoAux()
    {
        // Constructor
    }

    public ASenaoAuxSenaoComandoAux(
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PComandoAux _comandoAux_)
    {
        // Constructor
        setSenao(_senao_);

        setComandoAux(_comandoAux_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoAuxSenaoComandoAux(
            cloneNode(this._senao_),
            cloneNode(this._comandoAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoAuxSenaoComandoAux(this);
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PComandoAux getComandoAux()
    {
        return this._comandoAux_;
    }

    public void setComandoAux(PComandoAux node)
    {
        if(this._comandoAux_ != null)
        {
            this._comandoAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAux_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senao_)
            + toString(this._comandoAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._comandoAux_ == child)
        {
            this._comandoAux_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._comandoAux_ == oldChild)
        {
            setComandoAux((PComandoAux) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
