/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class TDecProcedimento extends Token
{
    public TDecProcedimento()
    {
        super.setText(">>>");
    }

    public TDecProcedimento(int line, int pos)
    {
        super.setText(">>>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecProcedimento(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecProcedimento(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecProcedimento text.");
    }
}
