/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class TFilha extends Token
{
    public TFilha()
    {
        super.setText("filha da classe");
    }

    public TFilha(int line, int pos)
    {
        super.setText("filha da classe");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFilha(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFilha(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFilha text.");
    }
}
