/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.lexer;

import java.io.*;
import jaca.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClasse(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFilha(line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOutput(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAmpersand(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoevirgula(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObj(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicializacao(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleano(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDecProcedimento(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdade(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumero(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdClasse(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgualdade(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorQue(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgualQue(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParEsq(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParDir(line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarra(line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazioNIgnorado(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {35, 35, 6}, {37, 37, 7}, {38, 38, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {46, 46, 16}, {47, 47, 17}, {48, 57, 18}, {58, 58, 19}, {59, 59, 20}, {60, 60, 21}, {61, 61, 22}, {62, 62, 23}, {65, 90, 24}, {95, 95, 25}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 26}, {101, 101, 29}, {102, 102, 30}, {103, 104, 26}, {105, 105, 31}, {106, 110, 26}, {111, 111, 32}, {112, 112, 33}, {113, 113, 26}, {114, 114, 34}, {115, 115, 35}, {116, 117, 26}, {118, 118, 36}, {119, 122, 26}, {123, 123, 37}, {124, 124, 38}, {192, 195, 39}, {199, 200, 40}, {201, 202, 41}, {204, 206, 42}, {210, 213, 43}, {217, 219, 44}, {224, 227, 45}, {231, 234, 46}, {236, 238, 47}, {242, 245, 48}, {249, 251, 49}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{0, 9, 50}, {11, 12, 50}, {14, 65535, 50}, },
            {},
            {},
            {{0, 9, 51}, {11, 12, 51}, {14, 65535, 51}, },
            {},
            {},
            {},
            {},
            {{48, 57, 52}, },
            {},
            {},
            {},
            {{44, 44, 53}, {48, 57, 54}, {69, 69, 55}, {101, 101, 56}, },
            {{61, 61, 57}, },
            {},
            {{61, 61, 58}, },
            {{61, 61, 59}, },
            {{62, 62, 60}, },
            {{65, 90, 61}, {95, 95, 62}, {97, 122, 63}, {192, 195, 64}, {199, 200, 65}, {201, 202, 66}, {204, 206, 67}, {210, 213, 68}, {217, 219, 69}, {224, 227, 70}, {231, 234, 71}, {236, 238, 72}, {242, 245, 73}, {249, 251, 74}, },
            {{65, 90, 75}, {97, 122, 76}, {192, 195, 77}, {199, 200, 78}, {201, 202, 79}, {204, 206, 80}, {210, 213, 81}, {217, 219, 82}, {224, 227, 83}, {231, 234, 84}, {236, 238, 85}, {242, 245, 86}, {249, 251, 87}, },
            {{65, 251, -26}, },
            {{65, 95, -26}, {97, 110, 63}, {111, 111, 88}, {112, 122, 63}, {192, 251, -26}, },
            {{65, 95, -26}, {97, 107, 63}, {108, 108, 89}, {109, 110, 63}, {111, 111, 90}, {112, 251, -29}, },
            {{65, 95, -26}, {97, 109, 63}, {110, 110, 91}, {111, 122, 63}, {192, 251, -26}, },
            {{65, 95, -26}, {97, 97, 92}, {98, 104, 63}, {105, 105, 93}, {106, 116, 63}, {117, 117, 94}, {118, 122, 63}, {192, 251, -26}, },
            {{65, 109, -31}, {110, 110, 95}, {111, 251, -31}, },
            {{65, 95, -26}, {97, 97, 63}, {98, 98, 96}, {99, 116, 63}, {117, 117, 97}, {118, 251, -32}, },
            {{65, 95, -26}, {97, 113, 63}, {114, 114, 98}, {115, 122, 63}, {192, 251, -26}, },
            {{65, 95, -26}, {97, 100, 63}, {101, 101, 99}, {102, 122, 63}, {192, 251, -26}, },
            {{65, 100, -36}, {101, 101, 100}, {102, 251, -36}, },
            {{65, 95, -26}, {97, 97, 101}, {98, 100, 63}, {101, 101, 102}, {102, 251, -36}, },
            {{0, 122, 103}, {124, 65535, 103}, },
            {},
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{0, 65535, -8}, },
            {{0, 12, -11}, {14, 38, 51}, {39, 39, 104}, {40, 65535, 51}, },
            {{48, 57, 52}, {69, 69, 105}, {101, 101, 106}, },
            {{48, 57, 52}, },
            {{48, 57, 54}, {69, 101, -54}, },
            {{45, 45, 107}, },
            {{45, 45, 107}, },
            {},
            {},
            {},
            {{62, 62, 108}, },
            {{65, 251, -26}, },
            {{65, 90, 24}, {95, 95, 62}, {97, 122, 26}, {192, 251, -2}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 90, 109}, {95, 95, 110}, {97, 122, 111}, {192, 195, 112}, {199, 200, 113}, {201, 202, 114}, {204, 206, 115}, {210, 213, 116}, {217, 219, 117}, {224, 227, 118}, {231, 234, 119}, {236, 238, 120}, {242, 245, 121}, {249, 251, 122}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 110, -29}, {111, 111, 123}, {112, 251, -29}, },
            {{65, 95, -26}, {97, 97, 124}, {98, 122, 63}, {192, 251, -26}, },
            {{65, 109, -31}, {110, 110, 125}, {111, 251, -31}, },
            {{65, 95, -26}, {97, 112, 63}, {113, 113, 126}, {114, 122, 63}, {192, 251, -26}, },
            {{65, 107, -30}, {108, 108, 127}, {109, 122, 63}, {192, 251, -26}, },
            {{65, 107, -30}, {108, 108, 128}, {109, 109, 129}, {110, 122, 63}, {192, 251, -26}, },
            {{65, 109, -31}, {110, 110, 130}, {111, 251, -31}, },
            {{65, 234, -26}, {236, 236, 72}, {237, 237, 131}, {238, 238, 72}, {242, 251, -26}, },
            {{65, 95, -26}, {97, 105, 63}, {106, 106, 132}, {107, 122, 63}, {192, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 110, -29}, {111, 111, 133}, {112, 251, -29}, },
            {{65, 95, -26}, {97, 97, 134}, {98, 251, -91}, },
            {{65, 109, -31}, {110, 110, 135}, {111, 251, -31}, },
            {{65, 113, -35}, {114, 114, 136}, {115, 251, -35}, },
            {{65, 113, -35}, {114, 114, 137}, {115, 251, -35}, },
            {{0, 122, 103}, {124, 124, 103}, {125, 125, 138}, {126, 65535, 103}, },
            {{0, 65535, -53}, },
            {{45, 45, 139}, },
            {{45, 45, 139}, },
            {{48, 57, 140}, },
            {},
            {{65, 251, -77}, },
            {{65, 90, 75}, {95, 95, 110}, {97, 251, -27}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 251, -77}, },
            {{65, 107, -30}, {108, 108, 141}, {109, 251, -94}, },
            {{65, 95, -26}, {97, 114, 63}, {115, 115, 142}, {116, 122, 63}, {192, 251, -26}, },
            {{65, 114, -126}, {115, 115, 143}, {116, 251, -126}, },
            {{65, 95, -26}, {97, 116, 63}, {117, 117, 144}, {118, 251, -32}, },
            {{65, 114, -126}, {115, 115, 145}, {116, 251, -126}, },
            {{65, 95, -26}, {97, 103, 63}, {104, 104, 146}, {105, 122, 63}, {192, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 227, -26}, {231, 231, 147}, {232, 234, 71}, {236, 251, -26}, },
            {{65, 95, -26}, {97, 98, 63}, {99, 99, 148}, {100, 122, 63}, {192, 251, -26}, },
            {{65, 100, -36}, {101, 101, 149}, {102, 251, -36}, },
            {{65, 98, -133}, {99, 99, 150}, {100, 251, -133}, },
            {{65, 107, -30}, {108, 108, 151}, {109, 251, -94}, },
            {{65, 219, -26}, {224, 226, 70}, {227, 227, 152}, {231, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 95, -26}, {97, 99, 63}, {100, 100, 153}, {101, 122, 63}, {192, 251, -26}, },
            {{0, 65535, -105}, },
            {{48, 57, 154}, },
            {},
            {{65, 251, -26}, },
            {{65, 114, -126}, {115, 115, 155}, {116, 251, -126}, },
            {{65, 95, -26}, {97, 115, 63}, {116, 116, 156}, {117, 122, 63}, {192, 251, -26}, },
            {{65, 95, -26}, {97, 97, 157}, {98, 251, -91}, },
            {{65, 110, -29}, {111, 111, 158}, {112, 251, -29}, },
            {{65, 95, -26}, {97, 97, 159}, {98, 251, -91}, },
            {{65, 226, -137}, {227, 227, 160}, {231, 251, -26}, },
            {{65, 95, -26}, {97, 104, 63}, {105, 105, 161}, {106, 122, 63}, {192, 251, -26}, },
            {{65, 115, -145}, {116, 116, 162}, {117, 251, -145}, },
            {{65, 100, -36}, {101, 101, 163}, {102, 251, -36}, },
            {{65, 251, -26}, },
            {{65, 110, -29}, {111, 111, 164}, {112, 251, -29}, },
            {{65, 95, -26}, {97, 97, 165}, {98, 251, -91}, },
            {},
            {{65, 100, -36}, {101, 101, 166}, {102, 251, -36}, },
            {{65, 251, -26}, },
            {{65, 109, -31}, {110, 110, 167}, {111, 251, -31}, },
            {{65, 251, -26}, },
            {{32, 32, 168}, {65, 251, -26}, },
            {{65, 110, -29}, {111, 111, 169}, {112, 251, -29}, },
            {{65, 110, -29}, {111, 111, 170}, {112, 251, -29}, },
            {{65, 110, -29}, {111, 111, 171}, {112, 251, -29}, },
            {{65, 99, -139}, {100, 100, 172}, {101, 251, -139}, },
            {{65, 251, -26}, },
            {{65, 99, -139}, {100, 100, 173}, {101, 251, -139}, },
            {{65, 251, -26}, },
            {{65, 115, -145}, {116, 116, 174}, {117, 251, -145}, },
            {{100, 100, 175}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{65, 104, -150}, {105, 105, 176}, {106, 251, -150}, },
            {{65, 100, -36}, {101, 101, 177}, {102, 251, -36}, },
            {{65, 110, -29}, {111, 111, 178}, {112, 251, -29}, },
            {{97, 97, 179}, },
            {{65, 95, -26}, {97, 108, 63}, {109, 109, 180}, {110, 251, -95}, },
            {{65, 251, -26}, },
            {{65, 251, -26}, },
            {{32, 32, 181}, },
            {{65, 100, -36}, {101, 101, 182}, {102, 251, -36}, },
            {{99, 99, 183}, },
            {{65, 109, -31}, {110, 110, 184}, {111, 251, -31}, },
            {{108, 108, 185}, },
            {{65, 115, -145}, {116, 116, 186}, {117, 251, -145}, },
            {{97, 97, 187}, },
            {{65, 110, -29}, {111, 111, 188}, {112, 251, -29}, },
            {{115, 115, 189}, },
            {{65, 251, -26}, },
            {{115, 115, 190}, },
            {{101, 101, 191}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 42, 42, 42, 42, 34, -1, 30, 3, -1, 37, 38, 28, 26, 16, 27, 20, 29, 23, -1, 4, 32, -1, -1, -1, -1, -1, -1, -1, 35, -1, -1, -1, -1, -1, -1, -1, -1, 41, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 39, -1, 23, -1, 23, -1, -1, 10, 33, 31, -1, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 17, 24, 24, -1, 2, -1, -1, -1, 13, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 24, 24, 24, 24, 24, 24, 5, 24, 24, 24, 24, 24, 24, 8, 24, 40, -1, 23, 11, 24, 24, 24, 24, 24, 24, 24, 24, 24, 12, 24, 24, 23, 24, 9, 24, 22, 24, 24, 24, 24, 24, 19, 24, 0, 24, -1, 15, 6, 7, 24, 24, 24, -1, 24, 21, 18, -1, 24, -1, 24, -1, 24, -1, 24, -1, 14, -1, -1, 1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
